# Generated by Django 4.0.5 on 2023-05-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты жөні')),
                ('coming', models.BooleanField(default=False, verbose_name='Бұйырса, келемін')),
                ('spouse', models.BooleanField(default=False, verbose_name='Жұбайыммен барамын')),
                ('I_cant_come', models.BooleanField(default=False, verbose_name='Өкінішке орай, келе алмаймын')),
            ],
            options={
                'verbose_name': 'шақыру',
                'verbose_name_plural': 'Тойға шақырулар',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Personal'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Journalist',
        ),
    ]
